import './js/header';
import './js/categoriesList';
import './js/fondsList';
import './js/content';
import './js/modalBook';
import './js/burgerMenu';
import './js/loginization';
import './js/shoppingList';
import './js/scrollup';
